# Maximum number of trials allowed
MaxTrials: 10

# Maximum number of trials allowed
MaxSessions: 15

# Condition List
Condition:
  - IN
  - OUT

# Activity List
Activity:
  - FP
  - WALK
  - CRAWL
  - STAND
  - STEP
  - RASC
  - SASC
  
