tag_descriptions: [
  {id: 18, size: 0.123, frame_id: front_torso},
  {id: 19, size: 0.146, frame_id: back_torso},
  {id: 16, size: 0.058, frame_id: left_wrist},
  {id: 17, size: 0.058, frame_id: left_arm},
  {id: 14, size: 0.058, frame_id: right_wrist},
  {id: 15, size: 0.058, frame_id: right_arm},
  {id: 13, size: 0.058, frame_id: left_front_leg_top},
  {id: 19, size: 0.058, frame_id: left_front_leg_middle},
  {id: 12, size: 0.058, frame_id: left_front_leg_bottom},
  {id: 4, size: 0.058, frame_id: right_front_leg_top},
  {id: 3, size: 0.058, frame_id: right_front_leg_middle},
  {id: 5, size: 0.058, frame_id: right_front_leg_bottom},
  {id: 10, size: 0.058, frame_id: left_back_leg_top},
  {id: 8, size: 0.058, frame_id: left_back_leg_bottom},
  {id: 6, size: 0.058, frame_id: right_back_leg_top},
  {id: 7, size: 0.058, frame_id: right_back_leg_bottom},
  {id: 11, size: 0.058, frame_id: head_front},
  {id: 2, size: 0.058, frame_id: head_back},
]
